
#ifndef TMEM_CFG_H
#define TMEM_CFG_H

#define TMEM_SMALL_ALIGNMENT_AUTO_ADJUST_SUPPORT (1)
#if TMEM_SMALL_ALIGNMENT_AUTO_ADJUST_SUPPORT
#define TMEM_SMALL_ALIGNMENT_AUTO_ADJUST
#endif

#endif /* end of TMEM_CFG_H */
